### ISSUE TITLE
How to use external storage?

### ISSUE THREAD

**Issue by gurbain** [klutchell/balena-mediaserver#648]
Hello,

I just discovered your project and I find it amazing. I'm actually considering switching my current custom mediaserver installation at home to this. It would make it 10x times easier to maintain and also much more protable.

Nonetheless, having access to an external storage is a non-negotiable feature, since my media server already exceed 1TB and this is likely to increase in the future. I could not find any convincing solutions to deal with external data storage shared between containers on the BalenaOS forums. I guessed you have been through the same reasoning and I wondered if you had any update on this matter.

Cheers!

**Comment by klutchell** [comment]
Hey @gurbain , good question!

There is a way to auto mount a USB disk on boot by adding a udev rule to `/mnt/boot/config.json` on your device.

e.g.
```json
  "os": {
    "udevRules": {
        "66": "ACTION==\"add\", SUBSYSTEMS==\"usb\", SUBSYSTEM==\"block\", ENV{ID_FS_USAGE}==\"filesystem\", RUN{program}+=\"/usr/bin/systemd-mount --no-block --automount=yes --collect $devnode /run/mount/ext\"\n"
    }
  }
```

Then, the container can be passed the mount path as a volume and will not have extra privileges or access to any other hardware:

```yaml
version: '2'
volumes:
  test-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /run/mount/ext
services:
  app1:
    build:
      context: ./app1
    volumes:
      - 'test-volume:/data'
```
I haven't tried this recently, or with this specific project, but if you have a test device and some time I would suggest giving it a try. This method should work without adding additional privileges or mount commands inside the service containers.

I would also like to test it out too but I admit to not having a lot of availability right now, so I wanted to share here first.
